/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class ChangeEmail extends SpeakeasyBase {
    /**
     * new email
     */
    @SpeakeasyMetadata()
    @Expose({ name: "email" })
    email?: string;
}
