/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { EmploymentEntry, EmploymentEntry$ } from "./employmententry";
import * as z from "zod";

export type EmploymentEntries = {
    values?: Array<EmploymentEntry> | undefined;
};

/** @internal */
export namespace EmploymentEntries$ {
    export type Inbound = {
        values?: Array<EmploymentEntry$.Inbound> | undefined;
    };

    export const inboundSchema: z.ZodType<EmploymentEntries, z.ZodTypeDef, Inbound> = z
        .object({
            values: z.array(EmploymentEntry$.inboundSchema).optional(),
        })
        .transform((v) => {
            return {
                ...(v.values === undefined ? null : { values: v.values }),
            };
        });

    export type Outbound = {
        values?: Array<EmploymentEntry$.Outbound> | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, EmploymentEntries> = z
        .object({
            values: z.array(EmploymentEntry$.outboundSchema).optional(),
        })
        .transform((v) => {
            return {
                ...(v.values === undefined ? null : { values: v.values }),
            };
        });
}
