/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { LifeCycleEntry } from "./lifecycleentry";
import { Expose, Type } from "class-transformer";

export class LifeCycleEntries extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: LifeCycleEntry })
    @Expose({ name: "values" })
    @Type(() => LifeCycleEntry)
    values?: LifeCycleEntry[];
}
