/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Report } from "./report";
import { Expose, Type } from "class-transformer";

/**
 * Company Reports
 */
export class Reports extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: Report })
    @Expose({ name: "views" })
    @Type(() => Report)
    views?: Report[];
}
