/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";

export class SchemeBasic extends SpeakeasyBase {
    @SpeakeasyMetadata({ data: "security, name=password" })
    password: string;

    @SpeakeasyMetadata({ data: "security, name=username" })
    username: string;
}
