/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class UpdateListItemRequest extends SpeakeasyBase {
    /**
     * Name of the item.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;

    /**
     * ID of the new hierarchy parent node.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "parentId" })
    parentId?: number;
}
