/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { z } from "zod";

export type UpdateFieldRequest = {
    /**
     * The description of the field.
     */
    description?: string | undefined;
    /**
     * The name of the field.
     */
    name?: string | undefined;
};

/** @internal */
export namespace UpdateFieldRequest$ {
    export type Inbound = {
        description?: string | undefined;
        name?: string | undefined;
    };

    export const inboundSchema: z.ZodType<UpdateFieldRequest, z.ZodTypeDef, Inbound> = z
        .object({
            description: z.string().optional(),
            name: z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v.description === undefined ? null : { description: v.description }),
                ...(v.name === undefined ? null : { name: v.name }),
            };
        });

    export type Outbound = {
        description?: string | undefined;
        name?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, UpdateFieldRequest> = z
        .object({
            description: z.string().optional(),
            name: z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v.description === undefined ? null : { description: v.description }),
                ...(v.name === undefined ? null : { name: v.name }),
            };
        });
}
