/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { VariableEntry } from "./variableentry";
import { Expose, Type } from "class-transformer";

/**
 * List of variable payments.
 */
export class VariableEntries extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: VariableEntry })
    @Expose({ name: "values" })
    @Type(() => VariableEntry)
    values?: VariableEntry[];
}
