/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { RFCDate } from "../../types";
import { EmployeeReference } from "./employeereference";
import { Expose, Transform, Type } from "class-transformer";

export class WorkPart extends SpeakeasyBase {
    /**
     * The employee's description.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "department" })
    department?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "reportsTo" })
    @Type(() => EmployeeReference)
    reportsTo?: EmployeeReference;

    /**
     * The employee's site.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "site" })
    site?: string;

    /**
     * The employee's employment start date
     */
    @SpeakeasyMetadata()
    @Expose({ name: "startDate" })
    @Type(() => String)
    @Transform(({ value }) => new RFCDate(value), { toClassOnly: true })
    startDate?: RFCDate;

    /**
     * The employee's title.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "title" })
    title?: string;
}
