/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class DeleteCompanyNamedListsListNameItemIdSecurity extends SpeakeasyBase {
    @SpeakeasyMetadata({ data: "security, scheme=true;type=http;subtype=basic" })
    basic?: shared.SchemeBasic;

    @SpeakeasyMetadata({
        data: "security, scheme=true;type=apiKey;subtype=header;name=Authorization",
    })
    bearer?: string;
}

export class DeleteCompanyNamedListsListNameItemIdRequest extends SpeakeasyBase {
    /**
     * The ID of the list item.
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=itemId" })
    itemId: string;

    /**
     * The internal name of the list.
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=listName" })
    listName: string;
}

export class DeleteCompanyNamedListsListNameItemIdResponse extends SpeakeasyBase {
    /**
     * HTTP response content type for this operation
     */
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * HTTP response status code for this operation
     */
    @SpeakeasyMetadata()
    statusCode: number;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;
}
