/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../shared";
import { AxiosResponse } from "axios";

export class GetPeopleIdentifierSecurity extends SpeakeasyBase {
    @SpeakeasyMetadata({ data: "security, scheme=true;type=http;subtype=basic" })
    basic?: shared.SchemeBasic;

    @SpeakeasyMetadata({
        data: "security, scheme=true;type=apiKey;subtype=header;name=Authorization",
    })
    bearer?: string;
}

export class GetPeopleIdentifierRequest extends SpeakeasyBase {
    /**
     * Whether to supply fields (paths) instead of empty list as a default in order  to not exceed data permitted.
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=fields" })
    fields: string[];

    /**
     * Whether to supply humanReadable values in JSON instead of machine-readable (default) format.
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=humanReadable" })
    humanReadable?: boolean;

    /**
     * employee id
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=identifier" })
    identifier: string;

    /**
     * Whether to include the additional "humanReadable" JSON node in the response.
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=includeHumanReadable" })
    includeHumanReadable?: boolean;
}

export class GetPeopleIdentifierResponse extends SpeakeasyBase {
    /**
     * HTTP response content type for this operation
     */
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * Employee
     */
    @SpeakeasyMetadata()
    employees?: shared.Employees;

    /**
     * Unexpected error.
     */
    @SpeakeasyMetadata()
    error?: shared.ErrorT;

    /**
     * HTTP response status code for this operation
     */
    @SpeakeasyMetadata()
    statusCode: number;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;
}
