/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as shared from "../../../sdk/models/shared";
import * as z from "zod";

export type GetPeopleIdEquitiesRequest = {
    /**
     * Employee ID.
     */
    id: string;
};

export type GetPeopleIdEquitiesResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * List of salary equity grants.
     */
    equityEntries?: shared.EquityEntries | undefined;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
};

/** @internal */
export namespace GetPeopleIdEquitiesRequest$ {
    export type Inbound = {
        id: string;
    };

    export const inboundSchema: z.ZodType<GetPeopleIdEquitiesRequest, z.ZodTypeDef, Inbound> = z
        .object({
            id: z.string(),
        })
        .transform((v) => {
            return {
                id: v.id,
            };
        });

    export type Outbound = {
        id: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetPeopleIdEquitiesRequest> = z
        .object({
            id: z.string(),
        })
        .transform((v) => {
            return {
                id: v.id,
            };
        });
}

/** @internal */
export namespace GetPeopleIdEquitiesResponse$ {
    export type Inbound = {
        ContentType: string;
        EquityEntries?: shared.EquityEntries$.Inbound | undefined;
        StatusCode: number;
        RawResponse: Response;
    };

    export const inboundSchema: z.ZodType<GetPeopleIdEquitiesResponse, z.ZodTypeDef, Inbound> = z
        .object({
            ContentType: z.string(),
            EquityEntries: shared.EquityEntries$.inboundSchema.optional(),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
        })
        .transform((v) => {
            return {
                contentType: v.ContentType,
                ...(v.EquityEntries === undefined ? null : { equityEntries: v.EquityEntries }),
                statusCode: v.StatusCode,
                rawResponse: v.RawResponse,
            };
        });

    export type Outbound = {
        ContentType: string;
        EquityEntries?: shared.EquityEntries$.Outbound | undefined;
        StatusCode: number;
        RawResponse: never;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetPeopleIdEquitiesResponse> = z
        .object({
            contentType: z.string(),
            equityEntries: shared.EquityEntries$.outboundSchema.optional(),
            statusCode: z.number().int(),
            rawResponse: z.instanceof(Response).transform(() => {
                throw new Error("Response cannot be serialized");
            }),
        })
        .transform((v) => {
            return {
                ContentType: v.contentType,
                ...(v.equityEntries === undefined ? null : { EquityEntries: v.equityEntries }),
                StatusCode: v.statusCode,
                RawResponse: v.rawResponse,
            };
        });
}
