/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as shared from "../../../sdk/models/shared";
import * as z from "zod";

export type PostPeopleIdVariableRequest = {
    /**
     * Variable payment to add.
     */
    variableEntry: shared.VariableEntry;
    /**
     * Employee ID.
     */
    id: string;
};

export type PostPeopleIdVariableResponse = {
    /**
     * HTTP response content type for this operation
     */
    contentType: string;
    /**
     * HTTP response status code for this operation
     */
    statusCode: number;
    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    rawResponse: Response;
};

/** @internal */
export namespace PostPeopleIdVariableRequest$ {
    export type Inbound = {
        VariableEntry: shared.VariableEntry$.Inbound;
        id: string;
    };

    export const inboundSchema: z.ZodType<PostPeopleIdVariableRequest, z.ZodTypeDef, Inbound> = z
        .object({
            VariableEntry: shared.VariableEntry$.inboundSchema,
            id: z.string(),
        })
        .transform((v) => {
            return {
                variableEntry: v.VariableEntry,
                id: v.id,
            };
        });

    export type Outbound = {
        VariableEntry: shared.VariableEntry$.Outbound;
        id: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, PostPeopleIdVariableRequest> = z
        .object({
            variableEntry: shared.VariableEntry$.outboundSchema,
            id: z.string(),
        })
        .transform((v) => {
            return {
                VariableEntry: v.variableEntry,
                id: v.id,
            };
        });
}

/** @internal */
export namespace PostPeopleIdVariableResponse$ {
    export type Inbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: Response;
    };

    export const inboundSchema: z.ZodType<PostPeopleIdVariableResponse, z.ZodTypeDef, Inbound> = z
        .object({
            ContentType: z.string(),
            StatusCode: z.number().int(),
            RawResponse: z.instanceof(Response),
        })
        .transform((v) => {
            return {
                contentType: v.ContentType,
                statusCode: v.StatusCode,
                rawResponse: v.RawResponse,
            };
        });

    export type Outbound = {
        ContentType: string;
        StatusCode: number;
        RawResponse: never;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, PostPeopleIdVariableResponse> = z
        .object({
            contentType: z.string(),
            statusCode: z.number().int(),
            rawResponse: z.instanceof(Response).transform(() => {
                throw new Error("Response cannot be serialized");
            }),
        })
        .transform((v) => {
            return {
                ContentType: v.contentType,
                StatusCode: v.statusCode,
                RawResponse: v.rawResponse,
            };
        });
}
