/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../../../sdk/models/shared";
import { AxiosResponse } from "axios";

export class PostCompanyNamedListsListNameSecurity extends SpeakeasyBase {
    @SpeakeasyMetadata({ data: "security, scheme=true;type=http;subtype=basic" })
    basic?: shared.SchemeBasic;

    @SpeakeasyMetadata({
        data: "security, scheme=true;type=apiKey;subtype=header;name=Authorization",
    })
    bearer?: string;
}

export class PostCompanyNamedListsListNameRequest extends SpeakeasyBase {
    /**
     * The <b>parentId</b> attribute is optional and only applies to hierarchy lists. When <b>parentId</b> is specified, the newly created list item will be placed under the specific hierarchy parent node.
     */
    @SpeakeasyMetadata({ data: "request, media_type=application/json" })
    newListItem: shared.NewListItem;

    /**
     * The internal name of the list.
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=listName" })
    listName: string;
}

export class PostCompanyNamedListsListNameResponse extends SpeakeasyBase {
    /**
     * HTTP response content type for this operation
     */
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * A new item is created. Please note that the ID of the newly created item may be textual or numeric depending on the list type.
     */
    @SpeakeasyMetadata()
    flatListItemId?: shared.FlatListItemId;

    /**
     * HTTP response status code for this operation
     */
    @SpeakeasyMetadata()
    statusCode: number;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;
}
