/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import * as shared from "../../../sdk/models/shared";
import { AxiosResponse } from "axios";

export class PutCompanyNamedListsListNameItemIdSecurity extends SpeakeasyBase {
    @SpeakeasyMetadata({ data: "security, scheme=true;type=http;subtype=basic" })
    basic?: shared.SchemeBasic;

    @SpeakeasyMetadata({
        data: "security, scheme=true;type=apiKey;subtype=header;name=Authorization",
    })
    bearer?: string;
}

export class PutCompanyNamedListsListNameItemIdRequest extends SpeakeasyBase {
    /**
     * You need to provide at least one of: <b>name</b> or <b>parentId</b>. Providing a name will rename the list item value. Providing the parent ID will move the hierarchy list item (together with its children) under the indicated parent node.
     */
    @SpeakeasyMetadata({ data: "request, media_type=application/json" })
    updateListItemRequest: shared.UpdateListItemRequest;

    /**
     * The ID of the list item.
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=itemId" })
    itemId: string;

    /**
     * The internal name of the list.
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=listName" })
    listName: string;
}

export class PutCompanyNamedListsListNameItemIdResponse extends SpeakeasyBase {
    /**
     * HTTP response content type for this operation
     */
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * HTTP response status code for this operation
     */
    @SpeakeasyMetadata()
    statusCode: number;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;
}
