/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SDK_METADATA, SDKOptions, serverURLFromOptions } from "../lib/config";
import * as enc$ from "../lib/encodings";
import { HTTPClient } from "../lib/http";
import { ClientSDK, RequestOptions } from "../lib/sdks";
import * as errors from "../sdk/models/errors";
import * as operations from "../sdk/models/operations";

export class Attendance extends ClientSDK {
    private readonly options$: SDKOptions;

    constructor(options: SDKOptions = {}) {
        super({
            client: options.httpClient || new HTTPClient(),
            baseURL: serverURLFromOptions(options),
        });

        this.options$ = options;
        void this.options$;
    }
    /**
     * Import attendance data
     *
     * @remarks
     * <b>Supported user types:</b> Service
     */
    async postAttendanceImportImportMethod(
        input: operations.PostAttendanceImportImportMethodRequest,
        options?: RequestOptions
    ): Promise<operations.PostAttendanceImportImportMethodResponse> {
        const headers$ = new Headers();
        headers$.set("user-agent", SDK_METADATA.userAgent);
        headers$.set("Content-Type", "application/json");
        headers$.set("Accept", "application/json");

        const payload$ =
            operations.PostAttendanceImportImportMethodRequest$.outboundSchema.parse(input);

        const body$ = enc$.encodeJSON("body", payload$.ImportAttendanceData, { explode: true });

        const pathParams$ = {
            importMethod: enc$.encodeSimple("importMethod", payload$.importMethod, {
                explode: false,
                charEncoding: "percent",
            }),
        };

        const path$ = this.templateURLComponent("/attendance/import/{importMethod}")(pathParams$);

        const security$ =
            typeof this.options$.security === "function"
                ? await this.options$.security()
                : this.options$.security;
        const securitySettings$ = this.resolveGlobalSecurity(security$);

        const response = await this.fetch$(
            {
                security: securitySettings$,
                method: "POST",
                path: path$,
                headers: headers$,
                body: body$,
            },
            options
        );

        const responseFields$ = {
            ContentType: response.headers.get("content-type") ?? "application/octet-stream",
            StatusCode: response.status,
            RawResponse: response,
        };

        if (this.matchResponse(response, 200, "application/json")) {
            const responseBody = await response.json();
            const result = operations.PostAttendanceImportImportMethodResponse$.inboundSchema.parse(
                {
                    ...responseFields$,
                    ImportAttendanceResponse: responseBody,
                }
            );
            return result;
        } else if (this.matchStatusCode(response, [400, 403])) {
            // fallthrough
        } else {
            const responseBody = await response.text();
            throw new errors.SDKError("Unexpected API response", response, responseBody);
        }

        return operations.PostAttendanceImportImportMethodResponse$.inboundSchema.parse(
            responseFields$
        );
    }
}
