/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SDKOptions, serverURLFromOptions } from "../lib/config";
import { HTTPClient } from "../lib/http";
import { ClientSDK } from "../lib/sdks";
import { Attendance } from "./attendance";
import { CustomTables } from "./customtables";
import { Documents } from "./documents";
import { Metadata } from "./metadata";
import { Objects } from "./objects";
import { Onboarding } from "./onboarding";
import { Payroll } from "./payroll";
import { People } from "./people";
import { Reports } from "./reports";
import { Tables } from "./tables";
import { Tasks } from "./tasks";
import { TimeOff } from "./timeoff";

export class Hibob extends ClientSDK {
    private readonly options$: SDKOptions;

    constructor(options: SDKOptions = {}) {
        super({
            client: options.httpClient || new HTTPClient(),
            baseURL: serverURLFromOptions(options),
        });

        this.options$ = options;
        void this.options$;
    }

    private _attendance?: Attendance;
    get attendance() {
        return (this._attendance ??= new Attendance(this.options$));
    }

    private _people?: People;
    get people() {
        return (this._people ??= new People(this.options$));
    }

    private _metadata?: Metadata;
    get metadata() {
        return (this._metadata ??= new Metadata(this.options$));
    }

    private _reports?: Reports;
    get reports() {
        return (this._reports ??= new Reports(this.options$));
    }

    private _documents?: Documents;
    get documents() {
        return (this._documents ??= new Documents(this.options$));
    }

    private _tasks?: Tasks;
    get tasks() {
        return (this._tasks ??= new Tasks(this.options$));
    }

    private _objects?: Objects;
    get objects() {
        return (this._objects ??= new Objects(this.options$));
    }

    private _onboarding?: Onboarding;
    get onboarding() {
        return (this._onboarding ??= new Onboarding(this.options$));
    }

    private _payroll?: Payroll;
    get payroll() {
        return (this._payroll ??= new Payroll(this.options$));
    }

    private _customTables?: CustomTables;
    get customTables() {
        return (this._customTables ??= new CustomTables(this.options$));
    }

    private _tables?: Tables;
    get tables() {
        return (this._tables ??= new Tables(this.options$));
    }

    private _timeOff?: TimeOff;
    get timeOff() {
        return (this._timeOff ??= new TimeOff(this.options$));
    }
}
